### ISSUE TITLE
Access JupyterHub from  oceanprotocol.com/DataScience

### ISSUE THREAD

**Issue by MarcusJones** [oceanprotocol/mantaray#26]
Website endpoint points to AWS JupyterHub server.

**Comment by kremalicious** [comment]
sounds like you need to set this up on DNS level and `oceanprotocol.com` entry currently just points to an S3 bucket, no server doing some smart route resolving. So might be easier for now to setup a sub domain for that, like `datascience.oceanprotocol.com`

**Comment by MarcusJones** [comment]
datascience.oceanprotocol.com looks great to me!

**Comment by kremalicious** [comment]
So you want a simple redirect? Meaning the url in the user's address bar will be replaced by whatever url we redirect to immediately when hitting that url. If so, we should use your originally suggested oceanprotocol.com/datascience

I mentioned the subdomain only if you want to do an actual url mapping, meaning the url in user's address bar stays and the whole JupyterHub notebook would be accessible via this url. This would be preferable to hide complicated urls or server IPs

**Comment by kremalicious** [comment]
See https://github.com/oceanprotocol/datascience
