### ISSUE TITLE
Logging users in JupyterHub

### ISSUE THREAD

**Issue by MarcusJones** [oceanprotocol/mantaray#37]
We would be interested to log who uses the JupyterHub server, record their GH user name, how much time they spend, more?

**Comment by ttmc** [comment]
Before you can do any of that, you have to write a privacy policy, make it available to users, and then follow it. That's certainly doable. I'm just commenting so you're aware there's more to it than adding some code or service integrations.

**Comment by ttmc** [comment]
In practice, the existing Ocean Protocol Privacy Policy would probably be updated to include the new stuff.

**Comment by MarcusJones** [comment]
Agreed!
